#pragma once

/* NKRO on startup */
#define FORCE_NKRO
#define QMK_KEYS_PER_SCAN 12
#define USB_POLLING_INTERVAL_MS 1
/* Layer count */
#define DYNAMIC_KEYMAP_LAYER_COUNT 9
/* QK_GESC side effects */
#define GRAVE_ESC_CTRL_OVERRIDE
/* Tapping */
#define RETRO_TAPPING
/* Vial support */
#define VIAL_KEYBOARD_UID {0x9C, 0x26, 0xB1, 0xAF, 0x7B, 0x91, 0xAC, 0x62}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }
/* Disabling some RGB Effects to reduce firmware size */
#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_ALL
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef ENABLE_RGB_MATRIX_HUE_WAVE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
