#pragma once

/* NKRO on startup */
#define FORCE_NKRO
#define QMK_KEYS_PER_SCAN 12
/* Layer count */
#define DYNAMIC_KEYMAP_LAYER_COUNT 7
/* QK_GESC side effects*/
#define GRAVE_ESC_CTRL_OVERRIDE
// disabling some RGB Effects to reduce firmware size.
#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_ALL
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef ENABLE_RGB_MATRIX_HUE_WAVE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
